name: upload
on:
  push:
    branches:
      - main

env:
  JFROG_NAMESPACE: "cloudops"
  JF_URL: ${{ secrets.JF_URL }}
  JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: modules
        run: npm install semantic-release @semantic-release/git @semantic-release/github -D
      - name: release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload:
    needs: release
    if: success()

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./sg

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform format check
        run: terraform fmt --recursive --check

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@v12
        continue-on-error: true
        with:
          skip_check: CKV2_AWS_12,CKV2_AWS_11,CKV2_AWS_19
          output_format: cli,sarif
          output_file_path: results.sarif

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4

      - name: Configure and publish to Artifactory
        run: |
          jf tfc --server-id-deploy=setup-jfrog-cli-server --repo-deploy=terraform-local-modules
          VERSION="${{ needs.release.outputs.new_version }}"
          echo "Publishing version: $VERSION"
          jf tf p --namespace=${JFROG_NAMESPACE} --provider=local --tag="$VERSION"
    

      
    
